### ISSUE TITLE
Тутор / I. Запустить MVP

### ISSUE THREAD

**Issue by a-matyukh** [easably/games#27]
## 🎯 Цель этапа
Запустить MVP-версию Тутора с его фундаментальными стратегическими направлениями, которые будут дальше развиваться на следующих этапах с согласованным планом развития.
- [x] ~ Геймификация
   - [x] добавить базовую геймификацию
      - [x] очки #19
      - [x] лидерборд #21
      - [x] словарь с ачивками #20 [#183](https://github.com/easably/context-tutor/issues/183)
   - [x] демо-коллекция первых слов в словарь #51
   - [x] утвердить план развития геймификации #48
- [x] ~ Интерфейс
   - [x] изменить текущий интерфейс на новый базовый, соответствующий текущей дизайн-системе
      - [x] прототип интерфейса #28
      - [x] имплементация интерфейса #32
   - [x] утвердить план развития интерфейса #39
- [x] ~ Монетизация
   - [x] добавить страницу магазина с первым товаром "Премиум-аккаунт"
   - [x] утвердить план развития монетизации #25

*Важно: без лишних действий! Нужно построить каркас площадки, поэтому мы не тратим время на украшения и свистульки, которые будут добавляться в будущих этапах (анимация, аудиоспрайты, детализация дизайна и прочее)*

## 🗓️ График работ этапа
~~~
👌 Выполнено
~~~
**Первая неделя (7-13 сентября, 0.37 спринт)**
   - [x] очки #19
   - [x] лидерборд #21

**Вторая неделя (14-20 сентября, 0.38 спринт)**
   - [x] прототип интерфейса #28
   - [x] словарь с ачивками #20 [#183](https://github.com/easably/context-tutor/issues/183)
   - [x] переписанные игры на модулях и с уровнями, доступные в тестере
      - [x] игра с самолётом #23
      - [x] игра с танками #24

**Третья неделя (21-27 сентября, 0.39 спринт)**
   - [x] имплементация интерфейса #32
   - [x] демо-коллекция первых слов в словарь #51
   - [x] прототип первой игры с интегрированным упражнением #68
   - [x] создать планы развития всех стратегических направлений
      - [x] геймификация #48
https://github.com/easably/UA/issues/22
      - [x] интерфейс #39
      - [x] монетизация #25

**Четвертая неделя (28 сентября - 4 октября, 0.40 спринт)**
   - [x] альфа-тестирование и багфикс
      - [x] бесконечная загрузка после нажатия кнопки "Следующее предложение #92
      - [x] коррекция словаря #94
      - [x] поправить индексы и длинны слов, в подготовленных сборниках слов #96
      - [x] коррекция нового интерфейса #95
      - [x] https://github.com/easably/context-tutor/issues/235
   - [x] подготовить прототип интерфейса к продуктовой работе #88
   - [x] проблемы первого потока "Изучение слов" (догфудинг, 10 новых слов)
      - [x] запоминается правильное написание слова, но не его значение и перевод #43
      - [x] излишняя фокусировка на упражнении #44

**Пятая неделя (5-9 октября, 0.41 спринт)**
   - [x] имплементация "Космолёта" #38
   - [x] альфа-тесты и багфикс
      - [x] финишные приготовления #105
      - [x] негативный сценарий во время игры и после финиша "win" https://github.com/easably/context-tutor/issues/251
   - [x] тесты и анализ
      - [x] подключить аналитику со Светой #104
   - [x] дополнительные работы
      - [x] убрать обязательную регистрацию #18
   - [x] формирование второго этапа дорожной карты
      - [x] расчистить [задачи Влада](https://github.com/orgs/easably/projects/1?card_filter_query=assignee%3AVlad-CSA)
      - [x] идеи и прототипы упражнений, отличных от текущих механик

___

**🎖️ Окончание этапа и запуск MVP - 9 октября 2020 года**
- [x] Старт MVP, версия 1.0!
